name: test
on: [workflow_dispatch]
jobs:
  SubActionTest:
    #if: github.repository != '0penBrain/FreeCAD' && !endsWith( github.ref, '/master' )
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir globalflowdir
      - run: touch globalflowdir/globalflowfile
      - uses: ./.github/workflows/testaction
      - run: ls -Ra .

  SubFlowTest:
    uses: subflow.yml
#Dummy
