name: test
on: [workflow_dispatch, push]
jobs:
  Succeed:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I succeed"
    
  Fail:
    runs-on: ubuntu-latest
    #continue-on-error: true
    steps:
      - name: test
        continue-on-error: true
        run: |
          set +e
          echo "I fail"
          cat thisfiledoesnotexist
          echo "Test"
          
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          set +e
          pip install codespell
          wget https://raw.githubusercontent.com/codespell-project/codespell/master/codespell_lib/data/dictionary.txt
          echo "adn" > testfile
          echo "====================="
          codespell --quiet-level 3 --summary --count -D dictionary.txt testfile 2>err.log 1>out.log
          ec=$?
          echo "====================="
          cat err.log
          echo "====================="
          cat out.log
          echo "====================="
          misspellings=$( { codespell --quiet-level 3 --summary --count -D dictionary.txt testfile > codespell.log ; } ) 2>&1
          echo "$misspellings"
          echo "====================="
          set -x
          if [ $(($misspellings)) -gt 0 ]
          then
            echo "FAIL"
          else
            echo "SUCCESS"
          fi
          echo "====================="

#  SubFlowTest:
#    uses: ./.github/workflows/subflow.yml
#Dummy
