name: test
on: [workflow_dispatch, push]
jobs:
  Succeed:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I succeed"
    
  Fail:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - run: echo "I fail" ; exit 1
        continue-on-error: true

#  SubFlowTest:
#    uses: ./.github/workflows/subflow.yml
#Dummy
