name: test
on: [workflow_dispatch]
jobs:
  SubActionTest:
    #if: github.repository != '0penBrain/FreeCAD' && !endsWith( github.ref, '/master' )
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir globalflowdir
      - run: touch globalflowdir/globalflowfile
      - uses: ./.github/workflows/testaction
      - run: ls -Ra .
      - name: test
        run: |
          echo "test<<EOD" >> $GITHUB_ENV
          echo "une chaine" >> $GITHUB_ENV
          echo "deux chaines" >> $GITHUB_ENV
          echo "trois chaines" >> $GITHUB_ENV
          echo "EOD" >> $GITHUB_ENV
      - run: echo "cool"
        if: always()

  SubFlowTest:
    uses: ./.github/workflows/subflow.yml
#Dummy
