name: test
on: [workflow_dispatch, push]
jobs:
  Succeed:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I succeed"
    
  Fail:
    runs-on: ubuntu-latest
    #continue-on-error: true
    steps:
      - name: test
        continue-on-error: true
        run: |
          set +e
          echo "I fail"
          cat thisfiledoesnotexist
          echo "Test"
          
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          [ 1 -gt 5 ]

#  SubFlowTest:
#    uses: ./.github/workflows/subflow.yml
#Dummy
