name: test
on: [workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    #if: github.repository != '0penBrain/FreeCAD' && !endsWith( github.ref, '/master' )
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/local-actions/testaction

#Dummy
